<!doctype html>

<!--[if lt IE 7 ]> <html class="ie ie6 no-js" lang="en"> <![endif]-->
<!--[if IE 7 ]>    <html class="ie ie7 no-js" lang="en"> <![endif]-->
<!--[if IE 8 ]>    <html class="ie ie8 no-js" lang="en"> <![endif]-->
<!--[if IE 9 ]>    <html class="ie ie9 no-js" lang="en"> <![endif]-->
<!--[if gt IE 9]><!--><html class="no-js" lang="en"><!--<![endif]-->
<!-- the "no-js" class is for Modernizr. -->

<head id="www-sitename-com" data-template-set="html5-reset">

	<meta charset="utf-8">

	<!-- Always force latest IE rendering engine (even in intranet) & Chrome Frame -->
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

	<!-- Project meta - description : content -->
	<meta name="description" content="We're creating documentary-style videos that showcase real companies and real workers who use Ford Super Duty trucks in their jobs." />
	
	<title>We Own Work | Team Detroit</title>

	<!-- CSS: screen, mobile & print are all in the same file -->
	<link rel="stylesheet" href="../_/css/style.css">

	<!-- all our JS is at the bottom of the page, except for Modernizr. -->
	<script src="../_/js/modernizr-2.0.6.min.js"></script>

</head>

<body>

<div class="wrapper">

	<?php include '../header.php'; ?>
	
	<div id="billboard-spacer"></div>
	
	<div class="billboard-wrapper billboard-ext-carousel">
		<ul class="fluidCarousel">
			<li class="activeCarousel">
				<div class="close-video">x</div>
				<h4></h4>
				<img src="../_/img/projects/we_own_work/billboard-1.jpg" alt="">
				<div class="youtube-video-holder" data="gEznhzPprwg"></div>
			</li>
			<li class="">
				<div class="close-video">x</div>
				<h4></h4>
				<img src="../_/img/projects/we_own_work/billboard-2.jpg" alt="">
				<div class="youtube-video-holder" data="Hh-xL-6MBy0"></div>
			</li>
			<li class=""><img src="../_/img/projects/we_own_work/billboard-3.jpg" alt=""></li>
			<li class=""><img src="../_/img/projects/we_own_work/billboard-4.jpg" alt=""></li>
			<li class=""><img src="../_/img/projects/we_own_work/billboard-5.jpg" alt=""></li>
			<li class=""><img src="../_/img/projects/we_own_work/billboard-6.jpg" alt=""></li>
			<li class=""><img src="../_/img/projects/we_own_work/billboard-7.jpg" alt=""></li>
			<li class=""><img src="../_/img/projects/we_own_work/billboard-8.jpg" alt=""></li>	
			<li class=""><img src="../_/img/projects/we_own_work/billboard-9.jpg" alt=""></li>											
		</ul>
	</div>

	<div class="segment-headline-wrapper clear below-carousel">
		
		<h2 class="center min-max"><a href="../work.php" alt="Back to Work"><div class="gridbox">GRID</div></a><span class="segment-header-spacer-ext">We Own Work</span></h2>
		<div class="carousel-navigation center min-max">
			<ul class="carousel-controller">
				<li class="prev-button"><a href="#prev">&larr; Previous</a></li>
				<li class="page-nate"><span class="page-of">1</span> of <span>12</span></li>
				<li class="next-button"><a href="#next">Next &rarr;</a></li>
			</ul>
		</div>
	</div>

	<div class="content-wrapper">

		<div class="content center min-max clearfix">

			<section class="content-info-wrapper double">

				<article class="content-info">
					
					<h3>Ford sells more heavy-duty trucks than any other company. Can’t argue with truth.</h3>

					<p>That means more guys are working the toughest jobs in the country with Super Duty trucks, more than any other competitive brand. We’re out to show that Super Duty is the only true heavy-duty work truck and we’re out to show why.</p>

					<p>Data obtained from POLK marketing breaks down the percentages of trucks as used in different industries. For example, in the Metal Mining industry, 74% of the trucks being used are Ford Super Duty. 19% are Silverado HD and 1% of them are Ram HD.</p>

					<p>To show why Super Duty leads in such numbers, we’re creating documentary-style videos that showcase real companies and real workers who use Super Duty trucks in their jobs. And we’re tying each story to a specific industry: Oil & Gas, Mining, Heavy Construction, etc.</p>

					<p>Additional content is generated by our customers who can enter our website and create a truck card that features their truck along with the work that they use it for. These truck cards can be viewed by the public and voted on for degree of toughness. Users can also share their truck card in the social space or embed it into their own webpage.</p>

					<p>We’re reviewing all the truck cards to choose appropriate work stories that we’ll feature in future videos. In some cases, Mike Rowe will appear in the video to help tell these stories of real people and the work they do with their Super Duty.</p>
					
				
					<ul class="content-info-social">
						<li>Share &rarr;</li>
						<li class="facebook"><a href="#linkedin">Facebook</a></li>
						<li class="twitter"><a href="#linkedin">Twitter</a></li>
						<li class="googleplus"><a href="#linkedin">Google+</a></li>
						<li class="emailit"><a href="#linkedin">Email</a></li>
					</ul>

				</article>
				
			</section>

			<aside class="content-quote-wrapper single">

				<div class="content-quote">

					 <!--<blockquote>
					 	<p>Now, the new Super Duty joins the assault in a comprehensive launch that’s befitting its status as the backbone of the Built Ford Tough franchise.</p>
					 	<p class="content-quote-author">&ndash; Steve Lyons <span>(Ford Division President)</span></p>
					 </blockquote>-->
				
				</div>

			</aside>
			
			<ul class="secondary-nav">
				<li class="secondary-nav-prev"><a href="explorer-live.php">Previous</a></li>
				<li class="secondary-nav-next"><a href="mustang-customizer.php">Next</a></li>
			</ul>
		
		</div>
		
	</div>

	<?php include '../footer.php'; ?>

</div>

<!-- here comes the javascript -->

<!-- Grab Google CDN's jQuery. fall back to local if necessary -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7/jquery.min.js"></script>
<script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.16/jquery-ui.min.js"></script>
<script>window.jQuery || document.write("<script src='_/js/jquery-1.7.1.min.js'>\x3C/script>")</script>

<!-- this is where we put our custom functions -->
<script src="../_/js/jquery.shadow-animation.min.js"></script>
<script src="../_/js/jquery.easing.1.3.js"></script>
<script src="../_/js/functions.js"></script>

<script>

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-XXXXXX-XX']);
  _gaq.push(['_trackPageview', 'teamdetroit:work:We Own Work']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>

</body>
</html>